### ISSUE TITLE
[Feature] A different hyperlink is preferred

### ISSUE THREAD

**Issue by Tiny-Snow** [wangzhukang/sduthesis#1]
I recommend the following colors:
- Hyperlink and citations: linkdarkblue: {0, 0.08, 0.45}
- Content: black

**Comment by wangzhukang** [comment]
Thank you for your suggestion! I've added a new command in the configuration file `config/main/config-main.tex` to customize hyperlink colors: `\definecolor{linkdarkblue}{rgb}{0,0.08,0.45}`. Users can now set a custom color (e.g., `linkdarkblue`) for hyperlinks in cross-references, citations, and URL links.
